### ISSUE TITLE
swank not starting on OSX using sbcl and libIL issue

### ISSUE THREAD

**Issue by maacl** [cbaggers/cepl#28] opened 2015-06-07 12:13 UTC
Swank does not start automatically when launching platform-specific/osx-sbcl-launch.sh but can I can start it manually using:

`(swank:create-server :port 4005)`

After installing sdl2, devil and assimp using hombrew I get the following error when running:

`(ql:quickload :cepl-default)`

`Unable to load any of the alternatives:
      ("libIL.dylib" "libIL.1.dylib")
      [Condition of type CFFI:LOAD-FOREIGN-LIBRARY-ERROR]`

**Comment by cbaggers** [comment] 2015-06-11 09:41
Cheers, the latest push should search all of `/usr/local` to find libs which will include your brew installs. Thanks gain for the help. I'll change `/usr/local/` to something sane in the near future

**Comment by dptd** [comment] 2016-03-31 17:03
Hello there,
Actually I have the same problem. I have just run everything as written on the official github page for OSX and after running sbcl with run-session.lisp the following error appears:
```
debugger invoked on a LOAD-FOREIGN-LIBRARY-ERROR in thread
#<THREAD "main thread" RUNNING {10029ACBA3}>:
  Unable to load any of the alternatives:
   ("libIL.dylib" "libIL.1.dylib")
```

Devil was installed via brew and libraries are there.
```
cd /usr/local

find . -name "libIL.dylib"
./Cellar/devil/1.7.8_1/lib/libIL.dylib
./lib/libIL.dylib

find . -name "libIL.1.dylib"
./Cellar/devil/1.7.8_1/lib/libIL.1.dylib
./lib/libIL.1.dylib
```

Any ideas?

**Comment by cbaggers** [comment] 2016-04-06 11:26
Damn, that is what this code was meant to help with https://github.com/cbaggers/cepl/blob/master/core/repl.lisp#L16

**Comment by cbaggers** [comment] 2016-04-06 11:29
Oh...is that search recursive? I wonder what would happen it we change:
`(let ((extra-package-dirs '("/opt/local/lib/" "/usr/local/")))`
to
`(let ((extra-package-dirs '("/opt/local/lib/" "/usr/local/" "/usr/local/lib")))`

@dptd  Would you mind testing that?

**Comment by dptd** [comment] 2016-04-06 15:30
@cbaggers Actually I tried that before writing the reply in this thread. No luck though - same error.

Just to make everything clear. I modified the following file:

> /Users/dptd/quicklisp/dists/quicklisp/software/cepl-release-quicklisp-7f65a8cd-git/core/**repl.lisp**

and have rerun the whole process step-by-step with the provided instructions. This is also why I started to believe that this is not a cepl issue at all. I found some information over the web about CFFI LOAD-FOREIGN-LIBRARY-ERROR but couldn't make it run (not yet at least).

**Comment by cbaggers** [comment] 2016-04-07 17:10
Sorry, one more basic question before digging deeper, is the sbcl you are using the x86 version or the amd64 version?

**Comment by dptd** [comment] 2016-04-07 17:56
It's me who should 'sorry' for taking your time! I am using SBCL 1.3.4 installed via brew. I believe it is amd64 by default but not 100% sure (there is an option to build a 32-bit version only which I haven't used).

Do you know any easy way to check that? From SBCL I tried the following:
```
* (lisp-implementation-type)
"SBCL"

* (lisp-implementation-version)
"1.3.4"
```

No information about the target architecture I am afraid. My system is x86_64.

**Comment by cbaggers** [comment] 2016-04-13 07:20
Try just typing `(member :X86-64 *features*)` in your repl and see what ya get :)

**Comment by dptd** [comment] 2016-04-13 15:34
Didn't know that - thanks! Here is the output.
```
* (member :X86-64 *features*)
(:X86-64)
*
```

**Comment by cbaggers** [comment] 2016-04-14 12:42
hmm then I wonder what version of libIL was installed. Not sure how to check that

**Comment by hollybagley** [comment] 2016-05-29 14:26
I saw this issue too. I provided the library path manually and got
```Unable to load foreign library (LIBIL.DYLIB-793).
  Error opening shared object "/usr/local/Cellar/devil/1.7.8_1/lib/libIL.1.dylib":
  dlopen(/usr/local/Cellar/devil/1.7.8_1/lib/libIL.1.dylib, 10): Symbol not found: _png_set_gray_1_2_4_to_8
  Referenced from: /usr/local/Cellar/devil/1.7.8_1/lib/libIL.1.dylib
  Expected in: flat namespace
 in /usr/local/Cellar/devil/1.7.8_1/lib/libIL.1.dylib.
   [Condition of type CFFI:LOAD-FOREIGN-LIBRARY-ERROR]

Restarts:
 0: [RETRY] Try loading the foreign library again.
 1: [USE-VALUE] Use another library instead.
 2: [TRY-RECOMPILING] Recompile il and try loading it again
 3: [RETRY] Retry loading FASL for #<CL-SOURCE-FILE "cl-devil" "il">.
 4: [ACCEPT] Continue, treating loading FASL for #<CL-SOURCE-FILE "cl-devil" "il"> as having been successful.
 5: [RETRY] Retry ASDF operation.
 --more--

Backtrace:
  0: (CFFI::FL-ERROR "Unable to load foreign library (~A).~%  ~A" #:LIBIL.DYLIB-793 "Error opening shared object \"/usr/local/Cellar/devil/1.7.8_1/lib/libIL.1.dylib\": ..)
  1: (CFFI::REPORT-SIMPLE-ERROR #:LIBIL.DYLIB-793 #<SIMPLE-ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:~%  ~A." {10045FEA13}>)
  2: (CFFI::LOAD-FOREIGN-LIBRARY-PATH #:LIBIL.DYLIB-793 "/usr/local/lib/libIL.dylib" NIL)
  3: ((FLET CFFI::%DO-LOAD :IN CFFI::%DO-LOAD-FOREIGN-LIBRARY) #<CFFI:FOREIGN-LIBRARY LIBIL.DYLIB-793> #:LIBIL.DYLIB-793 "/usr/local/lib/libIL.dylib")
  4: (CFFI::%DO-LOAD-FOREIGN-LIBRARY "/usr/local/lib/libIL.dylib" NIL)
  5: (CFFI:LOAD-FOREIGN-LIBRARY "/usr/local/lib/libIL.dylib" :SEARCH-PATH NIL)
  6: (CFFI:LOAD-FOREIGN-LIBRARY CL-DEVIL::IL :SEARCH-PATH NIL)
  7: (SB-FASL::LOAD-FASL-GROUP #S(SB-FASL::FASL-INPUT :STREAM #<SB-SYS:FD-STREAM for "file /Users/holly/.cache/common-lisp/sbcl-1.2.11-macosx-x64/Users/holly/quicklisp/dists/quicklisp/software/cl-devil-201..
  8: (SB-FASL::LOAD-AS-FASL #<SB-SYS:FD-STREAM for "file /Users/holly/.cache/common-lisp/sbcl-1.2.11-macosx-x64/Users/holly/quicklisp/dists/quicklisp/software/cl-devil-20150302-git/il.fasl" {10036C5FC3}> N..
  9: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<SB-SYS:FD-STREAM for "file /Users/holly/.cache/common-lisp/sbcl-1.2.11-macosx-x64/Users/holly/quicklisp/dists/quicklisp/software/cl-devil-20150302-git/il.fasl" ..
 10: (LOAD #P"/Users/holly/.cache/common-lisp/sbcl-1.2.11-macosx-x64/Users/holly/quicklisp/dists/quicklisp/software/cl-devil-20150302-git/il.fasl" :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FOR..
 11: (UIOP/UTILITY:CALL-WITH-MUFFLED-CONDITIONS #<CLOSURE (LAMBDA NIL :IN UIOP/LISP-BUILD:LOAD*) {10036C31DB}> ("Overwriting already existing readtable ~S." #(#:FINALIZERS-OFF-WARNING :ASDF-FINALIZERS)))
 12: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unavailable argument> #<unavailable argument> #<ASDF/LISP-ACTION:LOAD-OP :VERBOSE NIL> #<ASDF/LISP-ACTION:CL-SOURCE-FILE "cl-devil" "il">)
 13: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS (ASDF/LISP-ACTION:LOAD-OP ASDF/LISP-ACTION:CL-SOURCE-FILE)) #<ASDF/LISP-ACTION:LOAD-OP :VERBOSE NIL> #<ASDF/LISP-ACTION:CL-SOURCE-FILE "cl-devil" "il">) [fa..
 14: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)) #<ASDF/LISP-ACTION:LOAD-OP :VERBOSE NIL> #<ASDF/LISP-ACTION:CL-SOURCE-FILE "cl-devil" "il">) [fast-method]
 15: ((:METHOD ASDF/PLAN:PERFORM-PLAN (LIST)) ((#1=#<ASDF/LISP-ACTION:PREPARE-OP > . #2=#<ASDF/SYSTEM:SYSTEM "uiop">) (#3=#<ASDF/LISP-ACTION:COMPILE-OP > . #2#) (#<ASDF/LISP-ACTION:LOAD-OP > . #2#) (#1# . ..
 16: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
 17: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) ((#1=#<ASDF/LISP-ACTION:PREPARE-OP > . #2=#<ASDF/SYSTEM:SYSTEM "uiop">) (#3=#<ASDF/LISP-ACTION:COMPILE-OP > . #2#) (#<ASDF/LISP-ACTION:LOAD-OP > . #2#) (#..
 18: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
 19: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {1004986F83}> :VERBOSE NIL) [fast-method]
 --more--
```
Also the code in repl.lisp doesnt look like it's run until later than the load time

**Comment by cbaggers** [comment] 2016-05-29 15:35
This looks like it might be the issue.

`libpng` had a function called `_png_set_gray_1_2_4_to_8` but renamed it. This broke `devIL`, however the `devIL` developers fixed this a year ago. Looks like `brew` is still using the old version of `devIL` whilst having the new version of `libpng`

It's a pretty shitty state of affairs. Not sure exactly what to do next. I have taken a quick look at the common lisp library `read-png` but it is so slow compared to `devIL`.

Thoughts welcome

**Comment by dptd** [comment] 2016-10-05 16:36
@cbaggers Any update on this issue? I am now on macOS Sierra and I was wondering if I should give it another try. I would really like to learn some GLSL with Common Lisp. CEPL sounds awesome but I wasn't able to make it work on OSX.

**Comment by cbaggers** [comment] 2016-10-05 16:49
I'll be honest, I forgot. I have been working on ways to ship the C dependencies with the lisp package so this will not be a problem in future. I am moving to [SOIL]() which is an excellent library.

I am just install Devil with homebrew on my mac right now, so we will see how it goes.

In the meantime you might want to know that you only need devil when you want to load images, CEPL itself does not depend on devil. If you have generated a new project using CEPL you may have cepl.devil as a dependency there, you can remove that.

**Comment by dptd** [comment] 2016-10-05 17:05
No worries, big thanks for such a quick reply. To be honest I tried to find you on irc but you are not there right now so I decided to write this message. Anyway - after installing Devil via homebrew I have same error as before.

```
Unable to load any of the alternatives:
("libIL.dylib" "libIL.1.dylib")
[Condition of type CFFI:LOAD-FOREIGN-LIBRARY-ERROR]
```

Not sure how to provide the path manually like @magnetospheric did it before. After removing cepl.devil from *.asd it worked. Thanks!

**Comment by cbaggers** [comment] 2016-10-05 17:10
Jesus, I tried to install devil and after 20 mins it's nearly filled up my hard disk...wtf brew?!

I'll come on #lisp-games irc now :)

**Comment by jkordani** [comment] 2016-10-05 17:41
Finding the libraries on osx usually involves adding the macports or
homebrew installation directory to the cffi global variable.

**Comment by cbaggers** [comment] 2016-10-06 06:38
Hi @jkordani that is true, however if you have a look at @magnetospheric's comment a few up you can see the issue is not that the library itself cant be found, but that a particular symbol can't be found (unless we have two separate problems of course.

**Comment by cbaggers** [comment] 2016-10-06 06:43
I could hack things a little from the cepl.devil side. However cepl.devil is just a couple of extra functions which call [cl-devil](https://github.com/zkat/cl-devil). Really the fix needs to live there.

**Comment by cbaggers** [comment] 2016-10-06 07:15
I've thrown this in to cepl so that at least anything that depends of cepl will have these loaded.
https://github.com/cbaggers/cepl/blob/196239d09c7ccff98fcda1c6d678291ed1dc4142/core/ffi.lisp

**Comment by podiki** [comment] 2017-05-19 21:14
I'm not sure what the status is currently, but I had no problem on Sierra with brew loading cepl/devil/etc. I did not try directly using `cl-devlil` though.

**Comment by cbaggers** [comment] 2017-05-21 00:07
Thanks @podiki yeah I think I'll have to adopt cl-devil one day, but for now I use cl-soil (via the CL lib called `dirt`) or sdl2-image so this hasnt been urgent for a while.

I'll leave this open as I don't think raising an issue on cl-devil is going to get anything done

**Comment by podiki** [comment] 2017-05-21 19:58
All I meant is that on current versions everything for `cepl`, including the devil library requirement, all loads fine on macOS Sierra (contrary to above issues it seems). Loading images for textures in `cepl` also seems fine.

**Comment by cbaggers** [comment] 2017-05-21 22:42
Oh! Sweet :) thanks, sorry for the confusion there

**Comment by cbaggers** [comment] 2017-05-22 07:14
I'm going to tentatively close this. If anyone still sees the issue please resurrect this beast!

**Closed by cbaggers** 2017-05-22 07:14 UTC
