### ISSUE TITLE
"Could not create GL context" on Windows 7 x64 with GeForce GTX 460

### ISSUE THREAD

**Issue by mucuspig** [cbaggers/cepl#84] opened 2016-10-11 21:21 UTC
- (ql:quickload :cepl.sdl2)
  To load "cepl.sdl2":
  Load 1 ASDF system:
    cepl.sdl2
  ; Loading "cepl.sdl2"
  ..............
  (:CEPL.SDL2)
- (cepl:repl)

debugger invoked on a SDL2::SDL-RC-ERROR in thread
# <THREAD "main thread" RUNNING {100292C333}>:

  SDL Error (#<SDL-GLCONTEXT {#X00000000}>): Could not create GL context: p

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

(SDL2:GL-CREATE-CONTEXT #<SDL2-FFI:SDL-WINDOW {#X00673EB0}>)
0]

**Comment by mucuspig** [comment] 2016-10-11 21:52
Sorry here is a backtrace:

0] backtrace

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {100292C333}>
0: (SDL2:GL-CREATE-CONTEXT #<SDL2-FFI:SDL-WINDOW {#X00673EB0}>)
1: ((:METHOD CEPL.HOST:REQUEST-CONTEXT (T T T T T T T T T T T T T T T T)) 320 24
0 "CEPL REPL" NIL NIL 0 16 8 8 8 8 32 T NIL T NIL) [fast-method]
2: (CEPL.CONTEXT:MAKE-CONTEXT :WIDTH 320 :HEIGHT 240 :TITLE "CEPL REPL" :FULLSCR
EEN NIL :NO-FRAME NIL :ALPHA-SIZE 0 :DEPTH-SIZE 16 :STENCIL-SIZE 8 :RED-SIZE 8 :
GREEN-SIZE 8 :BLUE-SIZE 8 :BUFFER-SIZE 32 :DOUBLE-BUFFER T :HIDDEN NIL :RESIZABL
E T :GL-VERSION NIL)
3: (CEPL::INIT 320 240 "CEPL REPL" T NIL NIL)
4: (CEPL:REPL 320 240 NIL)
5: (SB-INT:SIMPLE-EVAL-IN-LEXENV (CEPL:REPL) #<NULL-LEXENV>)
6: (EVAL (CEPL:REPL))
7: (INTERACTIVE-EVAL (CEPL:REPL) :EVAL NIL)
8: (SB-IMPL::REPL-FUN NIL)
9: ((LAMBDA NIL :IN SB-IMPL::TOPLEVEL-REPL))
10: (SB-IMPL::%WITH-REBOUND-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-IMPL::TOPLEVE
L-REPL) {100401578B}>)
11: (SB-IMPL::TOPLEVEL-REPL NIL)
12: (SB-IMPL::TOPLEVEL-INIT)
13: ((FLET #:WITHOUT-INTERRUPTS-BODY-86 :IN SAVE-LISP-AND-DIE))
14: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))
15: ("foreign function: #x42E6FC")

**Comment by mucuspig** [comment] 2016-10-11 21:56
Is BUFFER-SIZE the Z-buffer size? 32 seems unlikely to work IMHO. Maybe 24 will work?

**Comment by mucuspig** [comment] 2016-10-11 22:26
The SDL2 graphics examples work well so it may not be SDL2's fault:

(asdf:load-system :sdl2/examples)
(sdl2-examples:basic-test)

**Comment by mucuspig** [comment] 2016-10-11 22:41
When I remove this line from line 46 of cepl.sdl2.lisp, it seems to avoid the error
      (sdl2:gl-set-attr :context-profile-mask 1)

And I get seemingly better results. The window now appears black rather than white. It prints out 3 or 4 blank lines, too:

(:CEPL.SDL2)
* (cepl:repl)
New context v4.2
-----------------
    CEPL-REPL
-----------------
NIL
*

**Comment by cbaggers** [comment] 2016-10-12 22:09
Hi @mucuspig, thanks for posting.
Are you using CEPL from quicklisp or have you pulled from git?

I haven’t built on windows in quite a long time unfortunately, I should really do that. I'll try this when I next have time and will get back to you.

Also what timezone are you in? maybe we could attach this over skype/ghangouts some time if I cant figure it out on my end?

**Comment by mucuspig** [comment] 2016-10-12 23:49
I was using SBCL and CEPL from quicklisp.

I'm a noob at lisp unfortunately. I don't use skype / ghangouts, sorry.

I tried the github stuff but it looks like cepl.host:window-size is undefined:

(defun window-dimensions (&optional (window *gl-window*))
  (cepl.host:window-size window))

I hacked around that but there is a further error regarding BUFFER-STREAM-START-BYTE:

;     The symbol "BUFFER-STREAM-START-BYTE" is not external in the %CEPL.TYPES p
ackage.
;
;       Line: 285, Column: 43, File-Position: 10662
;
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file C:\\Users\\ghinger\\quic
klisp\\dists\\quicklisp\\software\\cepl-release-quicklisp-efd98778-git\\core\\pi
pelines\\defpipeline.lisp" {1007575E33}>

**Comment by cbaggers** [comment] 2016-10-19 10:13
I'm sorry for the slow responses. Lot's of projects in flight.

Don't worry about pulling from git, there are a lot of related projects and it's a pain to clone them all. The quicklisp version should be working so I need to look into that.

I'm not going to get time to work on this until next week as I'm in Denmark and will only have my linux machine. Thanks for trying this out, we will get it to work eventually :)

**Comment by cbaggers** [comment] 2016-10-26 10:11
And my windows dev machine is fucked, great. Windows doesnt log me in as me now.
I'll get something set up when I can

**Comment by cbaggers** [comment] 2017-05-22 07:12
Bought a NUC to test this, but could not reproduce this on a recent release. I'm going to close this for now as the bootstrapping has been changed a lot since last year and this 'may' be fixed now. Feel free to reopen if you still have the issue (using latest CEPL release).

**Comment by cbaggers** [comment] 2017-05-22 07:13
Also this may get more stable when we move to using GL Core contexts only

**Closed by cbaggers** 2017-05-22 07:12 UTC
