### ISSUE TITLE
Unable to request OpenGL version

### ISSUE THREAD

**Issue by podiki** [cbaggers/cepl#148] opened 2017-04-23 00:23 UTC
With the most recent commits I am unable to start `cepl:repl` as specifying an OpenGL version no longer works. Instead, it only gets the default context which comes up as 3.0 on my Intel graphics (have not tried Nvidia, but that should work as default is higher version). Requesting a version higher than 3.0 that worked in the past and allowed `cepl:repl` to successfully work.

**Comment by cbaggers** [comment] 2017-04-24 09:46
Odd. There have also been related changes in the following:
- varjo
- cepl.sdl2
- skitter
- cepl.skitter

Not having latest `cepl.sdl2` is the most likely candidate for the cause of the issue. It was _meant_ to be backwards compatible but I made a last minute change that may have broken that. I'll look into it tonight

**Comment by podiki** [comment] 2017-04-24 15:15
You are correct, I hadn't cloned the latest `cepl.sdl2` or the `skitter` ones. Works now, but looks like I have to update the key handling code. You can close this issue unless you really wanted to be backwards compatible with the older `cepl.sdl2`, which was the quicklisp version.

**Comment by cbaggers** [comment] 2017-04-24 21:49
I've pushed a fix gl-version backwards compatibility earlier tonight.
That skitter issue is a problem though, I'll chat to you about that on your skitter issue

**Closed by cbaggers** 2017-04-24 21:49 UTC
