### ISSUE TITLE
clash with clx

### ISSUE THREAD

**Issue by chuchana** [cbaggers/cepl#56] opened 2016-05-11 15:25 UTC
I cannot load both `clx` and `cepl`. 

When I load clx first, I get this error when I try to load cepl:
``` 
"GL" is a package name, so it cannot be a nickname for "CL-OPENGL".
[Condition of type ASDF/FIND-SYSTEM:LOAD-SYSTEM-DEFINITION-ERROR]
```
When I load cepl first, I get this one when I try to load clx:
```
GL is a nickname for the package CL-OPENGL
[Condition of type SB-KERNEL:SIMPLE-PACKAGE-ERROR]
```

**Comment by PuercoPop** [comment] 2016-05-11 16:10
The issue is not with CEPL. But with clx and cl-opengl. CLX defines a [gl](https://github.com/sharplispers/clx/blob/master/gl.lisp) package and cl-opengl [nicknames the package cl-opengl with the name gl](https://github.com/3b/cl-opengl/blob/master/gl/package.lisp#L32)

**Comment by cbaggers** [comment] 2016-05-12 08:14
@chuchana: @PuercoPop is correct. I'm going to close this as it's not something I can fix.
In my mind it would be good to have CLX depend on cl-opengl and use that library. Maybe you could raise this issue with the CLX folks

**Closed by cbaggers** 2016-05-12 08:14 UTC

**Comment by chuchana** [comment] 2016-05-13 11:47
Thank you both for your answers. I will ask on the CLX side.
